### ISSUE TITLE
Apply LICENSE

### ISSUE THREAD

**Issue by ahmetb** [k0kubun/go-ansi#3]
Hello,

I think you actually need to add a file called LICENSE containing the MIT license, or add MIT license header to all your source files.

Putting "MIT License" in the readme isn't doing the job as most vendoring tools won't include the readme file. Please consider applying the license file propoerly. This came up at https://github.com/AlecAivazis/survey/issues/112#issuecomment-343269615 which inspired from this library and took it further, but they can't property give attribution and preserve your licensing.

**Comment by k0kubun** [comment]
Okay, I'll add it later
